Add query frontend to the quickstart script
thanos-io/thanos pull request #3372
Opened 2020-10-27 23:30 UTC by vears91

Closes #3304

Signed-off-by: Victor Araujo <vear91@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

## Verification

2020-10-28 09:23 UTC, bwplotka requested changes
Nice thanks! 

It looks amazing, except one thing that might be blocked first by https://github.com/thanos-io/thanos/issues/3373

2020-10-28 09:23 UTC, bwplotka commented on scripts/quickstart.sh
> +  ${THANOS_EXECUTABLE} query-frontend \
This is not how it suppose to work, unfortunately. Those replicas have to be separate for better horizontal scalability. This means there should be a load balancing in between - ideally round robin load balancer for better distribution.

We can add some nginx for it, but ideally, we could work towards this: https://github.com/thanos-io/thanos/issues/3373

Let me know if this makes sense :hugs:

2020-10-28 15:26 UTC, yeya24 commented on scripts/quickstart.sh
> +QUERY_FRONTEND_CACHE_VALIDITY=${QUERY_FRONTEND_CACHE_VALIDITY:-"0s"}
Let's use `6h` here

2020-10-28 15:26 UTC, yeya24 commented on scripts/quickstart.sh
> +QUERY_FRONTEND_CACHE_MAX_SIZE_ITEMS=${QUERY_FRONTEND_CACHE_MAX_SIZE_ITEMS:-0}
Let's set this to 2048

2020-10-28 15:26 UTC, yeya24 commented on scripts/quickstart.sh
> +QUERY_FRONTEND_CACHE_MAX_SIZE=${QUERY_FRONTEND_CACHE_MAX_SIZE:-""}
Let's set this to `"0"`

2021-01-09 13:56 UTC, closed without merging

2021-02-12 09:10 UTC, kakkoyun commented
@vears91 Do you want to continue working on it? I can open it and give it another round of review. Sorry if we dropped the ball on this one.

2021-02-16 12:48 UTC, vears91 commented
> @vears91 Do you want to continue working on it? I can open it and give it another round of review. Sorry if we dropped the ball on this one.

Hi. I would like to, is https://github.com/thanos-io/thanos/issues/3373 still blocking this?