Nomitate kakkoyun as release shepherd for the v0.20.0 release
thanos-io/thanos pull request #3778
Opened 2021-02-09 11:42 UTC by kakkoyun

2021-02-09 12:31 UTC, squat requested changes
Can we break up this PR into two separate things? It seems to me that the rule changes are unrelated

2021-02-09 13:04 UTC, kakkoyun commented
@squat Whaatt? I don't know how those changes are ended up there 😅 😅 😅  Cleaning it.

2021-02-09 21:01 UTC, squat approved these changes

2021-02-09 21:02 UTC, merged

2021-02-10 08:41 UTC, bwplotka reviewed
Thanks a lot @kakkoyun  ❤️