mixin: Add namespace to the alerts
thanos-io/thanos pull request #3856
Opened 2021-03-01 11:08 UTC by kakkoyun

Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

* Add namespace to the alerting rules and annotations

## Verification

* `make examples`
* `make example-rules-lint`

2021-03-01 16:36 UTC, bwplotka reviewed
I would love this PR, but unfortunately, it also has those `pod` selector changes, which I don't understand 🤔

2021-03-05 06:54 UTC, kakkoyun commented
Friendly ping @metalmatze @bwplotka

2021-03-05 10:14 UTC, brancz commented
Didn't we just work on getting rid of kubernetes specific things?

2021-03-05 10:23 UTC, kakkoyun commented
Yes, definitely @brancz. I'll be introducing further changes to provide a more abstract solution for this https://github.com/thanos-io/thanos/issues/3867. It'll require more consideration. This would solve our problems in the short-term.

2021-03-05 10:41 UTC, kakkoyun commented
Ok, I'm convinced that we need to generalize this. Marking it WIP and jumping to fix these.

2021-03-09 09:28 UTC, kakkoyun commented
Friendly ping @bwplotka @metalmatze @brancz. Could you please take one last look at it?

2021-03-09 18:33 UTC, bwplotka requested changes
I wonder if we should not have `by (job, namespace)` in most of those places to ensure we are not reducing all to one value. If we have multiple jobs in different namespaces we would count those as one  series with this PR, no? 🤔

2021-03-09 18:33 UTC, bwplotka commented on examples/dashboards/bucket_replicate.json
> +                     "expr": "sum(rate(thanos_replicate_replication_runs_total{result=\"error\", job=\"$job\"}[$interval])) / sum(rate(thanos_replicate_replication_runs_total{job=\"$job\"}[$interval]
should we do `by (job, namespace)` here?

2021-03-09 18:33 UTC, bwplotka commented on examples/dashboards/bucket_replicate.json
> +                     "expr": "sum by (result) (rate(thanos_replicate_replication_runs_total{result=\"error\", job=\"$job\"}[$interval]))",
ditto

2021-03-09 18:33 UTC, bwplotka commented on examples/dashboards/overview.json
> +                     "expr": "sum(rate(http_requests_total{job=\"$job\", handler=\"query\",code=~\"5..\"}[$interval])) / sum(rate(http_requests_total{job=\"$job\", handler=\"query\"}[$interval]))",
We have to do by (job, namespace ) otherwise we sum things by all the things, no?

2021-03-10 07:44 UTC, kakkoyun commented
@bwplotka As stated in the issue(https://github.com/thanos-io/thanos/issues/3867) we try to decouple from any platforms by removing specific notions from the mixin. Thus I removed `namespace` from all the examples. However, we provide a flexible way to add any hierarchy to the alerts and dashboards through configuration. So it's okay to remove `namespace`. I have already added the necessary changelog entry.

2021-03-10 11:12 UTC, bwplotka requested changes
I understand that, however, the problem is that we are summing namespaces and potentially cluster (whatever users have) into one value.

2021-03-10 11:12 UTC, bwplotka commented on examples/dashboards/bucket_replicate.json
> +                     "expr": "sum(rate(thanos_replicate_replication_runs_total{result=\"error\", job=\"$job\"}[$interval])) / sum(rate(thanos_replicate_replication_runs_total{job=\"$job\"}[$interval]
Let me comment jsonnet code instead, but this example can mislead people - some of them maybe even copies those example 🤔

2021-03-10 11:12 UTC, bwplotka commented on mixin/dashboards/compact.libsonnet
> +            'sum by (job, group) (rate(thanos_compact_group_compactions_total{%s}[$interval]))' % selector,
I think we might want to put `(%(aggregators)s)`. The reason is that by removing namespace we allow multiple namespaces (and clusters - which was before) to be part of this aggregation. So suddenly we are returning sum-med number of group compactions, not one. And it's hidden to the dashboard user, I know it's a tedious work, but it sounds crucial to me 🤔

2021-03-10 12:54 UTC, kakkoyun commented
Thanks for pointing out. I'll make sure all the queries are modified with this way.

2021-03-12 09:55 UTC, kakkoyun commented
@bwplotka It's ready for another round. I've added missing aggregators.

2021-03-19 12:47 UTC, bwplotka reviewed
Looks perfect now, very flexible and consistent. But I would suggest bit different naming 🤗

2021-03-19 12:47 UTC, bwplotka commented on mixin/README.md
> +  // Hierarcies is a way to help mixin users to add high level hierarcies to their alerts and dashboards.
Thanks for mini docs <3

2021-03-19 12:47 UTC, bwplotka commented on mixin/README.md
> +  // Hierarcies is a way to help mixin users to add high level hierarcies to their alerts and dashboards.
WDYT `groupby` or `groups` or `tagets`?

```suggestion
  // Groups <slice?> is a way to help mixin users to add high level target grouping to their alerts and dashboards.
```

2021-03-19 12:47 UTC, bwplotka commented on mixin/README.md
> +    aggregator: ['%s' % level for level in std.objectFields(thanos.hierarcies)],
WDYT?

```suggestion
    dimensions: ['%s' % level for level in std.objectFields(thanos.hierarcies)],
```
https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators

2021-03-19 12:47 UTC, bwplotka commented on mixin/README.md
> +  // Hierarcies is a way to help mixin users to add high level hierarcies to their alerts and dashboards.
Actually, I don't understand why hierarchies are helpful here and why we need them? Can we just show in an example `dimensions/aggregators: job, namespace, cluster`?

2021-03-19 12:47 UTC, bwplotka commented on mixin/README.md
> +    aggregator: ['%s' % level for level in std.objectFields(thanos.hierarcies)],
Reason is.. aggregator is `sum, max, min` etc 🤗

2021-03-19 12:50 UTC, bwplotka commented on mixin/dashboards/sidecar.libsonnet
> +            ['time() - max by (%s) (thanos_objstore_bucket_last_successful_upload_time{%s})' % [utils.joinLabels([thanos.sidecar.dashboard.aggregator, 'bucket']), thanos.sidecar.dashboard.selector]],
Quite understandable (`bucket` label addition)!

2021-03-19 14:14 UTC, bwplotka approved these changes
Epic, looks clean and amazing to me! 💪🏽 Let's go! 🚀

2021-03-19 14:14 UTC, merged