sidecar: Mark sidecar as unhealthy if bucket upload fails
thanos-io/thanos pull request #3857
Opened 2021-03-01 13:57 UTC by LittleChimera

* [ ] I added CHANGELOG entry for this change.

## Changes

Health probe flips to unhealthy if sidecar upload to a bucket fails. This would enable restarting the sidecar with liveliness probe in a containerised environment and reload config on restart.

## Verification

TODO

2021-03-01 15:23 UTC, kakkoyun requested changes
Hey @LittleChimera, thanks for the PR.
However, I'm not sure about this change, this will mark sidecar unhealthy as soon as it encounters an error while uploading. The sidecar also responses to the queries. Even though uploading blocks when enabled is pat of the SLA, this shouldn't just mark the process as unhealthy. We should be more clear about this.

2021-03-01 17:03 UTC, LittleChimera commented
thanks for the feedback @kakkoyun!
yeah, you have a good point - it's important that sidecar can still be used as a querier even if uploading fails for some time. However, I think this change could still go hand in hand with that. If you had a default Kubernetes probes with readiness pointing to `/-/ready` and liveness pointing to `/-/healthy`, the pod would still be able to receive traffic for some time even if the liveness probe is failing. With this change, only liveliness probe is flipped. I think a good approach in this case would be to set combination `failureThreshold`  and `periodSeconds` on liveness probe to something reasonable to operators so that sidecar doesn't restart too often in case of more permanent error. Consequently, operators can still ensure required availability of the sidecar to respond to queries.

2021-03-01 17:33 UTC, LittleChimera commented
> semantically speaking, would it be better if uploader probe was added as a separate probe to `prober.Combine(...)`?

2021-03-02 10:16 UTC, LittleChimera commented
@GiedriusS to simplify a bit what I meant - service health being degraded (i.e. marked as unhealthy) doesn't have to trigger immediate restart of the service. Depending on what kind of expectations the operators have, they might configure the service to keep running in degraded state for some time to try to let it recover on its own (no liveness probe or delayed), stop traffic (readiness probe), or restart immediately (liveness probe with no delay).

For thanos-sidecar, I think it would make most sense if liveness probe failed after upload has been failing for some longer time (e.g. 10 minutes), or if it hasn't been responding properly to queries for a shorter time (e.g. 30s). I think that timing decision for both of these should be left to the external system rather than trying to implement this logic into the sidecar itself.

2021-03-11 10:31 UTC, kakkoyun reviewed
I still think it's not a sufficient solution to mark the sidecar as unhealthy and restart when uploads start to fail. We promote alerts for these reasons. Errors could come from different directions. This would prevent the sidecar to run under the degraded state.

We should focus one what we actually try to solve here, `Detect credentials changes without application restarts`. We want to dynamically reload the credentials for the bucket, right? Let's focus on that. If it needs a relatively bigger change, we are happy to accept design proposals 🤗 

Let's go back to design boards and try attacking this issue from another direction. For that, I'm closing this PR.

2021-03-11 10:31 UTC, closed without merging