When encountering damaged data, continue to compress other data.
thanos-io/thanos pull request #4072
Opened 2021-04-17 11:58 UTC by mikechengwei

Optimize: #4046 

## Changes

When encountering damaged data, continue to compress other data.

2021-04-17 13:00 UTC, mikechengwei commented
/test end-to-end tests

2021-04-20 15:36 UTC, bwplotka commented on pkg/compact/compact.go
> +			level.Error(cg.logger).Log("msg", "gather index issues for block ", bdir, err)
In the local scope, this fix is great, but unfortunately, if we don't deal with this and just ignore it, the next compaction will pick the same set of blocks (: 

Let's think about automated solution to this problem. Ideally while changing compactor algorithm: https://github.com/thanos-io/thanos/issues/4046#issuecomment-823373171

2021-04-20 15:37 UTC, bwplotka requested changes
Thanks for this attempt, but we need to invest in different planning and mechanisms that allows this as commented as https://github.com/thanos-io/thanos/issues/4046#issuecomment-823373171 

Hope that makes sense 🤗

2021-04-20 15:43 UTC, mikechengwei commented
/

2021-04-20 15:43 UTC, closed without merging