Cut 0.23.0 release.
thanos-io/thanos pull request #4666
Opened 2021-09-16 13:59 UTC by bwplotka

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

## Verification

2021-09-16 15:37 UTC, kakkoyun requested changes

2021-09-16 15:37 UTC, kakkoyun commented on CHANGELOG.md
> +## [v0.23.0](https://github.com/thanos-io/thanos/tree/release-0.23) - 2021.09-16
```suggestion
## [v0.23.0](https://github.com/thanos-io/thanos/tree/release-0.23) - 2021.09.16
```

2021-09-16 17:31 UTC, bwplotka commented on CHANGELOG.md
> +## [v0.23.0](https://github.com/thanos-io/thanos/tree/release-0.23) - 2021.09-16
Fixed, thanks!

2021-09-16 17:52 UTC, yeya24 commented
Can we have https://github.com/thanos-io/thanos/pull/4657 as well?

2021-09-20 07:09 UTC, yeya24 commented
I'd like to have https://github.com/thanos-io/thanos/pull/4681 to get into this release as well. With the `EndpointSet` change introduced in 0.23.0, federated proxy APIs are enabled automatically so #4681 is definitely necessary to have.

2021-09-20 08:22 UTC, bwplotka commented
Thanks for pointing, let me look

2021-09-20 08:45 UTC, bwplotka commented
Closing for now, let's do 0.23.0-rc.1 first.

2021-09-20 08:45 UTC, closed without merging