store: Avoid 404 errors on deletion-mark.json
thanos-io/thanos pull request #5180
Opened 2022-02-23 16:06 UTC by garc33

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Check deletion-mark.json meta file exists before to retrieve it in order to avoid http 404 issues.

## Verification

2022-02-24 08:28 UTC, GiedriusS reviewed
Could you please elaborate on what do you mean by
```
it in order to avoid http 404 issues.
```
? What are "HTTP 404 issues"?

2022-02-24 08:29 UTC, GiedriusS commented on pkg/block/metadata/markers.go
>  	r, err := bkt.ReaderWithExpectedErrs(bkt.IsObjNotFoundErr).Get(ctx, markerFile)
The code here should handle this, no? :thinking:

2022-04-27 19:04 UTC, akanshat requested changes

2022-04-27 19:04 UTC, akanshat commented on pkg/block/metadata/markers.go
> +		return errors.Wrapf(err, "file exists: %s", metaFile)
I think you need to update the name from `metaFile` to `markerFile` to avoid the errors here.

2022-07-31 04:22 UTC, closed without merging