Created .devcontainer.json file for Github codespaces
thanos-io/thanos pull request #5661
Opened 2022-08-30 13:10 UTC by Akshit42-hue

Signed-off-by: Akshit42-hue <patelakshit2025@gmail.com>

Issue #5464

2022-08-30 13:28 UTC, Akshit42-hue commented
cc @douglascamata @yeya24

2022-08-30 13:56 UTC, douglascamata requested changes

2022-08-30 13:56 UTC, douglascamata commented on .devcontainer/devcontainer.json
> +    	"dockerFile": "",
Identation here seems off.

2022-08-30 13:56 UTC, douglascamata commented on .devcontainer/devcontainer.json
> +
Just one empty line instead of two to separate logical keys is enough.

2022-08-30 14:00 UTC, douglascamata commented
I tried to create a Codespace from your branch and it failed:

```
2022-08-30 13:56:53.713Z: Configuration starting...
2022-08-30 13:56:53.788Z: $ git -C "/var/lib/docker/codespacemount/workspace" clone --branch main --depth 1 https://github.com/Akshit42-hue/thanos "/var/lib/docker/codespacemount/workspace/thanos"
2022-08-30 13:56:53.843Z: Cloning into '/var/lib/docker/codespacemount/workspace/thanos'...
2022-08-30 13:56:58.867Z: git process exited with exit code 0
2022-08-30 13:56:58.899Z: $ git -C "/var/lib/docker/codespacemount/workspace/thanos" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
2022-08-30 13:56:58.917Z: git process exited with exit code 0
2022-08-30 13:57:00.069Z: @microsoft/vscode-dev-containers-cli 0.66.0.
2022-08-30 13:57:00.089Z: Start: Resolving Remote
2022-08-30 13:57:00.103Z: $ docker ps -q -a --filter label=Type=codespaces
2022-08-30 13:57:00.120Z: Stop (36 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-08-30 13:57:00.133Z: $ /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/thanos --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/thanos/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-08-30 13:57:00.210Z: @microsoft/vscode-dev-containers-cli 0.66.0.
2022-08-30 13:57:00.226Z: $ docker buildx version
2022-08-30 13:57:00.376Z: Stop (185 ms): Run: docker buildx version
2022-08-30 13:57:00.392Z: Start: Resolving Remote
2022-08-30 13:57:00.414Z: $ docker ps -q -a --filter label=Type=codespaces
2022-08-30 13:57:00.433Z: Stop (36 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-08-30 13:57:00.447Z: Error: EISDIR: illegal operation on a directory, read
2022-08-30 13:57:00.460Z: Stop (342 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/thanos --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/thanos/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-08-30 13:57:00.473Z: Exit code 1
2022-08-30 13:57:00.486Z: Failed to create container.
2022-08-30 13:57:00.506Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/thanos --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/thanos/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-08-30 13:57:00.521Z: Error Code: 1302
2022-08-30 13:57:00.538Z: Container creation failed.
2022-08-30 13:57:00.559Z: 
2022-08-30 13:57:00.590Z: Creating recovery container.
```

I think you don't need to provide neither the `context` nor `dockerfile` keys in the devcontainer configuration.

2022-08-30 14:03 UTC, douglascamata requested changes
Please do use a json formatter to format the configuration file.

2022-08-30 14:03 UTC, douglascamata commented on .devcontainer/devcontainer.json
> +
Why this blank line?

2022-08-30 14:03 UTC, douglascamata commented on .devcontainer/devcontainer.json
> +		"vscode": {
Inconsistent start of object here (on new line vs on same line).

2022-08-30 14:03 UTC, douglascamata commented on .devcontainer/devcontainer.json
> +						"go.gopath": "/go"
Missing indentation for keys inside object.

2022-08-31 20:44 UTC, yeya24 commented on .devcontainer/devcontainer.json
> +}
Need an empty line

2022-09-01 09:04 UTC, douglascamata approved these changes
LGTM! 

I tried to create a Codespace from your fork, @Akshit42-hue, and it worked well. Thanks!

2022-09-02 06:53 UTC, yeya24 commented
Can you mark this as ready for review?

2022-09-02 07:49 UTC, yeya24 approved these changes
Thanks!

2022-09-02 07:49 UTC, merged