Query: Add pop-up when Explain Checkbox is disabled
thanos-io/thanos pull request #6662
Opened 2023-08-25 18:45 UTC by lmarques03

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Adds suggestion made in #6632 

## Verification

2023-08-26 08:13 UTC, MichaHoffmann requested changes
Couldnt we just hide this button if the prometheus engine is selected?

2023-08-26 12:53 UTC, lmarques03 commented
> Couldnt we just hide this button if the prometheus engine is selected?

I can do that if you prefer it that way :)

2023-08-28 05:21 UTC, saswatamcode commented
> Couldnt we just hide this button if the prometheus engine is selected?

Well yeah, but I'd like users to know that the feature exists, even if they default to `prometheus` engine. So disabling instead of hiding completely would be a way to do that. That way they'd be more proactive in trying it out. Wdyt @MichaHoffmann? 🙂

2023-08-28 05:28 UTC, saswatamcode reviewed
Generally LGTM but you might want to fix the commits, so only your changes exist on the branch. 🙂

2023-08-28 05:28 UTC, saswatamcode commented on pkg/store/bucket.go
> +		l, err = decodePostings(b)
I think the order of commits is a bit strange here. This change is unrelated to this PR.

2023-08-28 05:28 UTC, saswatamcode commented on pkg/ui/react-app/src/components/Checkbox.tsx
> +          <div className="popup-message">This functionality is only available when using the Thanos engine</div>
Let's explain the feature too.
```suggestion
          <div className="popup-message">Explain allows you to view an expandable query plan of the PromQL query similar to SQL EXPLAIN. This functionality is only available when using the Thanos engine</div>
```

2023-08-28 06:51 UTC, MichaHoffmann commented
> > Couldnt we just hide this button if the prometheus engine is selected?
> 
> Well yeah, but I'd like users to know that the feature exists, even if they default to `prometheus` engine. So disabling instead of hiding completely would be a way to do that. That way they'd be more proactive in trying it out. Wdyt @MichaHoffmann? 🙂

Okay fair enough! Lets proceed with the tooltip!

2023-09-11 06:58 UTC, saswatamcode approved these changes
LGTM!

2023-09-11 06:59 UTC, merged