Cut 0.33.0-rc.0
thanos-io/thanos pull request #6841
Opened 2023-10-24 15:49 UTC by MichaHoffmann

2023-10-24 16:02 UTC, metalmatze approved these changes
Looks good. 
If this is what needs to be done. I guess there was a bot that writes all the changes into the changelog, right?

2023-10-24 16:02 UTC, metalmatze commented on docs/release-process.md
I'd say to make these changes directly to `main` but they'll eventually merge back, so it should be fine.

2023-10-24 19:00 UTC, fpetkovski approved these changes

2023-10-24 19:07 UTC, yeya24 commented on docs/release-process.md
+1 to have this change in main. Better to be a separate pr

2023-10-24 19:08 UTC, yeya24 approved these changes

2023-10-24 20:39 UTC, squat commented on docs/release-process.md
> -| v0.33.0 | (planned) 2023.10.03 | TBD                           |
this change is causing the docs check to fail

2023-10-24 20:40 UTC, squat requested changes
lgtm - the change to the VERSION doc, which is causing CI to fail

2023-10-25 03:25 UTC, saswatamcode approved these changes
LGTM! Just need to fix the docs check. 
I think it might be a bit more convenient to prep `main` first for v0.33 via a PR like: https://github.com/thanos-io/thanos/pull/6617

Otherwise, you might get a bunch of merge conflicts

2023-10-26 03:59 UTC, saswatamcode approved these changes
Thanks! Let's get this rolling.

2023-10-26 04:00 UTC, merged